/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.discoveri.predikt3.test.sentencegen;

import eu.discoveri.predikt3.cluster.DocumentCategory;
import eu.discoveri.predikt3.graph.Populate;
import eu.discoveri.predikt3.graph.SentenceNode;
import eu.discoveri.predikt3.sentences.LangCode;

import java.io.IOException;
import java.util.List;


/**
 *
 * @author chrispowell
 */
public class DocSentsFromText
{
    public static void main(String[] args)
            throws IOException
    {   
        // Set up OpenNLP (TokenizerME, SentenceDetectorME, POSTaggerME, [Simple]Lemmatizer)
        System.out.println("... Setup NLP");
        Populate popl = new Populate( LangCode.en );
        
        List<SentenceNode> lsn = popl.extractSentences(longDoc,new DocumentCategory(99));
        
        
    }
    
    // Ridiculous length "string"
    static String longDoc = "No one can escape change in 2020. After a year of retrogrades, supermoons, and eclipses, the year will end with what astrologers are calling the \"Great Conjunction.\" This meeting between Jupiter and Saturn, which goes down on Monday, December 21, sets into action a course of events that will shape the next 20 years. For better or worse, personally and globally, major shifts are being set into action. So, how do you ensure that you see positive changes over this time, such as more money and great sex coming your way, rather than business losses and break-ups? Keep reading, but here's a hint: To properly set yourself up, you'll have to get focused and shake off any situations or people who only act as harmful distractions. Buckle up and read on. 2020 Overall\n" +
"Right from the get-go, 2020 asks us to make tough decisions. There is a full moon and lunar eclipse in Cancer on Friday, January 10. Lunar eclipses usually mean endings, which plays well into what happens two days later. On Sunday, January 12, Saturn (the planet of restrictions) conjuncts Pluto (the planet of death and rebirth) in business-minded Capricorn. Do you have one too many side projects? Are you dating people you're pretty 'meh' about? Cut 'em loose. This transit asks you to identify your goals and focus your energy on them. Those who work hard will be rewarded while those who spread themselves too thin will lose out. Yes, it's a tough ask, but you can do it. There are also full moons that double as lunar eclipses in Sagittarius on Friday, June 5, in Capricorn on Sunday, July 5, and in Gemini on Monday, November 30.\n" +
"2020 is also riddled with super moons, which are full moons during which the moon is closest to the earth. These are powerful times for manifestation. Mark them in your calendar as great dates to launch a professional project or practice sex magick. This year's supermoons occur in Leo on Sunday, February 9, in Virgo on Monday, March 9, in Libra on Wednesday, April 8, and Scorpio on Thursday, May 7. Everyone's love life may feel a little shaky during Venus retrograde from Wednesday, May 13 to Thursday, June 25. Venus rules beauty, love, and wealth. When she goes retrograde, communication in our love life tanks. The best way to survive is to practice lots of self-care because the better you feel, the more empathetic and loving you are to your partner(s).\n" +
"While bubble baths and massages are encouraged, avoid making major changes to your appearance during this time. It sounds like a scary retrograde, but it's an opportunity to examine how we express ourselves romantically. If we're brave enough to notice where we can improve and make the effort to do so, Venus retrograde can do wonders for your love life. Oh, and exes may appear during this time. It's actually even worse than Mercury retrograde in that regard. Towards the end of Venus retrograde on Sunday, June 21 there is a new moon and solar eclipse in Cancer. Eclipses are fun to watch but cause shake-ups and drama. It's best to stay inside having sex, reading, or getting a massage. A second solar eclipse happens in Sagittarius on Monday, December 14.\n" +
"Another major retrograde, Mars retrograde, occurs from Wednesday, September 9, to Saturday, November 14. Warrior planet Mars is about ambition, aggression, and hot sex. When it goes retrograde, we find ourselves craving softer intimacy. It's not the best time to make major business deals or plan an orgy, but it's perfect for making your lover breakfast in bed. We're all feeling lazy. The more you struggle against the effects of Mars retrograde, the harder this period is. So relax and take a nap (or 20).\n" +
"While 2020 asks us to focus and cut away what's no longer serving is, the year also encourages us to become more involved with our community. Especially during an election year, it's a great time to become involved with like-minded people. Lucky planet Jupiter enters humanitarian Aquarius on Saturday, December 19. Get out of the house, attend a local meet-up, or go to a party you've always been curious about. The friends you make now play a major role in your life for years to come.\n" +
"2020 ends with a massive celestial occurrence on Monday, December 21, that astrologers are calling the Great Jupiter-Saturn conjunction. What happens now creates massive change on a global and personal level and affects our course of action for the next 20 years. No pressure, right? Cut out distractions, focus on what matters, and get involved in your community. That is the recipe for success in 2020.\n" +
"December Predictions, By Zodiac Sign\n" +
"Aries (March 21 – April 19)\n" +
"Your ruling planet, Mars, goes retrograde this year. However, being the warrior fire sign that you are, you come out on top, with more money and sex than ever. Read your full 2020 horoscope here.\n" +
"Taurus (April 20 – May 20)\n" +
"Venus is your ruling planet, and it's going retrograde in 2020. Your job is not to be distracted by exes. They will try to haunt you this year, but you're above that. Read your full 2020 horoscope here.\n" +
"Gemini (May 21 – June 20)\n" +
"The energy of 2020 freaks you out at first when you find yourself wanting to focus on one partner instead of 20. There's nothing wrong with multiple partners, but with all the money-making opportunities in front of you, someone is on the chopping block. Read your full 2020 horoscope here.\n" +
"Cancer (June 21 – July 22)\n" +
"2020 is the year you stop people-pleasing. Go after your dreams, Cancer. If you don't, they might not be there for much longer. Read your full 2020 horoscope here.\n" +
"Leo (July 23 – August 22)\n" +
"You're a lion, Leo, and don't you forget it. 2020 requires strength — do not dull your shine for anyone. Those who try to cut you down get thrown to the sharks. Read your full 2020 horoscope here.\n" +
"Virgo (August 23 – September 22)\n" +
"You're the sign of service, Virgo, but 2020 asks you to step into a leadership role. Can you handle it? Read your full 2020horoscope here.\n" +
"Libra (September 23 – October 22)\n" +
"You're all about relationships, from friends, to partners, to people you just flirt with over text. But this year, someone has to go. You can't do it all and make all this money. Read your full 2020 horoscope here.\n" +
"Scorpio (October 23 – November 21)\n" +
"Put down the stinger and turn on the charm. Go after what you want. This year asks you to practice emotional regulation for the sake of networking. Read your full 2020 horoscope here.\n" +
"Sagittarius (November 22 – December 21)\n" +
"You are so fabulous, Sagittarius, so why are you still hung up on your ex? Everyone has something to let go of this year, and yours is that unnecessary nostalgia. Read your full 2020 horoscope here.\n" +
"Capricorn (December 22 – January 19)\n" +
"2020 is your year, Capricorn. You basically own it. Does that turn you on? Good. Get started on that project you've had on the backburner. Read your full 2020 horoscope here.\n" +
"Aquarius (January 20 – February 18)\n" +
"2020 finds you dreaming of love — maybe even long-term commitment. Who are you and what have you done with our Aquarius rebel? Don't worry, you can have your metaphorical wedding cake and eat it too. Read your full 2020 horoscope here.\n" +
"Pisces (February 19 – March 20)\n" +
"You'll find yourself craving structure this year, but you might also want a new sexual partner. Stop swiping. 2020 introduces you to great people IRL, but it's up to you to get out there. Read your full 2020 horoscope here.\n" +
"General 2021 Horoscope:\n" +
"They say change is the universal law of nature. The old has to give way to the new, which is the way things work out and move on. And we are going to witness another significant change in the flow of time. Yes, the year 2020 is leaving us making way for the year 2021.\n" +
"While the horoscope 2021 promises good times ahead, there are things that may not be under our control and we may have to be more conscious about it. This is why we are here to help you with our 2021 astrology predictions.\n" +
"And the year 2021 is all set to bring positive changes for all the Zodiac signs. The year 2021 will bring good vibes and happiness for the people at large. Though there will be dark aspects also, you can manage the situation if you take proper steps. We know that you are eagerly waiting for the 2021 horoscope predictions. Towards this, our team of experienced astrologers offers you a detailed analysis of your astrology 2021. Knowing 2021 predictions will help you command a better hold over your life and destiny.\n" +
"Your future predictions 2021 predict that you will look at the positive sides of the future. As you will get to know about your future in detail, you will be better equipped to devise a strategy to improve your life and your growth & development prospects. You will have a better understanding of life. You will be in a commanding position and will be able to decide & direct your own destiny and future.\n" +
"The new year horoscope 2021 will include detailed forecasts and predictions about the upcoming year for each Zodiac sign. Our expert astrologers are here to make your life simpler by suggesting detailed remedies for your problems along with your 2021 astrology forecasts. So read on and know what is in store:\n" +
"Aries Horoscope 2021: Aries Horoscope 2021: You Will Need To Stay Positive\n" +
"As seen in the Aries horoscope 2021, the year 2021 is likely to begin on a very positive note and it may also grant you the ease of working and a general good fortune. Gradually, relations with friends and associates are likely to improve. Around the mid-2021, certain planetary situations may bring new challenges on the career front. Kindly keep control of your negative thoughts during this period. During the latter half of 2021, your major professional ambitions are likely to get fulfilled so says the Aries 2021 horoscope. But, astrology advises you to control your temper otherwise you may lose certain relations shows Aries astrology prediction 2021. To know about your relationships in the year 2021, access your Free Personalized 2021 Report.\n" +
"As per the 2021 Aries horoscope, you may become prosperous and experience growth in your financial status. In other words, you will be successful in monetary planning, so say the astrologers. It is a good time for long-term investments, but do not get lured into greedy schemes. There will be some phases in which your expenses will be more thus you may experience a little financial constraint. Hence, you are advised to stay away from adventurous speculations in the share market this year. During the ending months of this year, you may have better opportunities for gain and growth.\n" +
"Aries 2021 Horoscope: You Will Gain Focus And Concentration\n" +
"As far as your love and relationship are concerned, you will be blessed with the positive cosmic powers for your love life according to Aries 2021. Your concentration this year should be only on enjoying rather than the expectations as per the findings of astrology. You will keep on getting the support and love of your partner most of the time this year. You will also notice that your partner will be more active than before and this will give you good days of intimacy as well. However, there will also be some days in which love and intimacy may be a little less but just remember that this is just a passing phase. As the year progresses, your partner’s support for making love will increase gradually shows your zodiac sign.\n" +
"Regarding your educational and academic arenas, planets will be moving in your favor according to Aries yearly prediction 2021. In this entire year, you will put in a lot of effort mixed with some struggle related to your studies. However, there will also be some mental pressure regarding studies but you will succeed in all your tasks and examinations. This is going to make you feel immensely happy. There will be some days in which you may feel some laziness too but remember this is just a passing phase. In certain phases, you will be very serious about your studies in terms of progress and overall development in accordance with the Aries horoscope 2021.\n" +
"Taurus Horoscope 2021: Taurus Horoscope 2021 – The Phase Of Gains And Growth\n" +
"The planetary situations will remain supportive of your professional life as per Taurus 2020 horoscope. You will grow in terms of knowledge and personality during this phase and you will do very well in your career. You will find new and creative ways to get things done and this is going to make things better for you. You are likely to see benefits to your undertakings. Overall, you will be in a happy mood due to which your performance will also increase. However, there will also be some days when you will feel demotivated. But, as the period progresses, planetary situations as per Taurus astrology 2021 seem beneficial for your career growth and expansion. You are likely to feel more confident and enthusiastic about your ability to earn as in the Taurus 2021 horoscope. Get Free Personalized 2021 Report! Know whether your confidence helps you grow in career and business.\n" +
"As on the financial front, the year may begin on a satisfactory note says the Taurus 2021 predictions. You will receive a lot of opportunities that will be beneficial. However, there will be some phases when you may face some expenses about social commitments. As the year progresses, you will receive good opportunities for growth in fortune and gain in wealth. The middle parts of 2021 will be a good time for long-term investments. It is a good time to implement your economic plans. As the year progresses post-mid-September 2021, you will try to take your financial status to a new height with a decisive plan and new thinking pattern. But do not get tense, suggests your astrology. Aries Horoscope 2021 Shows You Will Seek More Freedom\n" +
"The 2021 Aries horoscope shows that as far as your married and domestic lives are concerned, most of 2021 shall grant you tremendous success. Your desire for freedom will increase and you may not want to get tied up to tedious routine life. However, there will also be some days in which certain emotional issues might complicate things a little and might add up to your stress and frustration, says your yearly predictions. So, don’t let these situations create any distance between you and your loved ones. There will also be phases in which you may expect some changes in your domestic life. Before making any decision for change, you need to speak to your loved ones and see if they will be able to manage it as well advises the findings from your zodiac sign.\n" +
"As far as your relationship is concerned, you will be maintaining a good rapport with friends, and they will inspire you or enthuse you. You will be filled with positive energy on most of the days. Your mind will be very sharp, and therefore your energy will be spent behind reflexes as seen in Aries 2021 predictions. However, there will be some days when you will feel very low. But, your thoughts and vibrations will surely be positive. In such days, you should try to remain calm and composed while dealing with anything and everything. Overall, your mental, physical and emotional quotients will remain high during major parts of 2021. Access the Free Personalized 2021 Report to know what the stars have in store for you.\n" +
"2021 Aries Horoscope: An Overview\n" +
"It is seen that some of your long-standing aims and ambitions can come to fruition. Besides, you will be blessed with positive cosmic energy in matters of love and relationship. Your thoughts and vibrations will be surely positive. On the whole, your mental, physical and emotional capabilities will remain high as per Aries yearly horoscope 2021.\n" +
"2021 Taurus Horoscope Shows Good Positive Vibrations\n" +
"As far as your love and relationship segment is concerned, you will have good positive and beneficial vibrations of your destiny which will give you better results than before. The Taurus horoscope 2021 states this year will be the most important and decisive in your relationship to take your love life to a new stage. Intimacy and good days are there but the over expectations may hurt you on certain days. There would be some days during this year wherein you will have to control your negative emotions and refrain yourself from speaking harsh and bitter words. There would be days of enjoyment and love with intimacy but some delay on certain days. Overall, you may notice that the favourable celestial energies are working positively as compared to the previous year shows the Taurus 2021 horoscope. How will the cosmic energies influence your life in 2021? To know the answer, access the Free Personalized 2021 Report!\n" +
"The Taurus astrology prediction 2021 shows that as far as your education and academic segments are concerned, this year may prove to be supportive and beneficial to accomplish your expectations. In other words, this year is going to benefit you in numerous ways. But, you should avoid being lazy and should study and revise all your subjects daily. Make the best use of every important thing that could take you closer to your dreams. People who have been trying to attempt the exams for the second time also will pass during this phase. Opportunities don’t come always, and you have to go for it when you get it, indicates your Taurus horoscope 2021. Especially the mid-year is going to be a good time for you to answer any entrance tests or examinations, so say the astrologers. Hence, don’t be lazy this time around and submit your assignments and projects on time. On the whole, the major part of this year 2021 appears good for you as a lot of golden opportunities are going to come your way in accordance with the 2021 Taurus horoscope. Taurus Horoscope 2021 Will Help You Clear Your Doubts\n" +
"As for your conjugal and family life, you need to work on finding out what it is to improve the present state of your marriage and family life, says the Taurus 2021 horoscope. Several commitments towards your family and closed ones are very important if you want everything to be smooth enough. Jupiter’s benefic aspect will help you to clear doubts, confusion, and uncertainties in your relationship as seen in the Taurus astrology 2021. However, there will be some phases in which planets will teach you some lessons and may also push you to understand the value of commitment. Further, your tendency toward seeking more playfulness may cause problems in your relationship. This may create some distance between you and your loved one, in accordance with your Taurus yearly prediction 2021.\n" +
"In the health and fitness segments of Taurus 2021, most of the months this year seem very beneficial in which you will experience sound health but mood swings are likely to affect your performance. Due to Jupiter and Saturn’s auspicious transits, you will remain energetic and fit. During the middle months, it will be the best time to invest your energy behind some serious projects. During the second half, you will be very happy with the outcome of several important areas. This is the best time to spend time playing outdoor games and having fun-time with people you like as per Taurus 2021 yearly predictions. Access the Free Personalized 2021 Report! Know about your bonding with your life partner in 2021.\n" +
"Taurus 2021 Horoscope: An Overview\n" +
"On the whole, the year 2021 will help the Taurus zodiac sign natives grow professionally and personally. The developments during this year will support you in healthy and happy living shows your yearly prediction. There will be positive vibrations that will help you in strengthening your bonding and relationship with others. However, you will need to understand the value of commitment in your relationships. Besides, you should be cautious against mood swings showing the Taurus horoscope 2021 prediction.\n" +
"Gemini Horoscope 2021: Gemini Horoscope 2021 – You Will Be Blessed With Good Fortune\n" +
"The Gemini horoscope 2021 prediction shows the very special year 2021 for the Gemini natives. This will be a year where you will be happy with the support of luck and even the reduction of obstacles that were following you for a long time. This will be a year where Gemini zodiac will finally put an end to old issues and start afresh. You will be grateful to the transit of Jupiter in Aquarius whose aspect is also seen upon the Gemini zodiac sign. It would be a year where many of your planning will also come true if executed promptly, with dedicated focus. So, fasten your seat for a much better ride in 2021, as seen in the Gemini astrology 2021.\n" +
"As in Gemini 2021, income is one area where Gemini natives will be happy in 2021 to see it rise. Income through speculative sources will be rewarding if you are careful of the investments that you undertake at the start of the year. Going long-term in investing will also be rewarding. However, if you are clear to take an investment position mid-term or willing to take a risk in derivative products, then you must seek an expert option before taking this position. This will optimize your gains and you will get settled with something significant in accordance with Gemini yearly prediction 2021. See your career prospects in more detail. Avail the Free Personalized 2021 Report!\n" +
"Gemini Horoscope 2021: A Good Year For Romance\n" +
"Further, the year is also good for natives looking for a romantic relationship. The singles will easily mix with their opponents and shall fall into a relationship. Therefore, the aspect of Jupiter upon your sign and also upon the zodiac sign of Libra will be encouraging. Libra zodiac sign is the house of romance and relationship for Gemini zodiac and the aspect is considered highly auspicious. Thus, the year is also good for native already into a relationship. The duo will finally decide to settle down in a married relationship and this will bring you both closer to each other, states the Gemini horoscope 2021.\n" +
"The year 2021 is also good for students pursuing higher studies. Students will be highly enthusiastic and energetic to learn new subjects and even master the same. The Gemini natives, planning to work and learn will find the year to be highly beneficial as seen in the Gemini 2021 horoscope. As Saturn in the house of Capricorn will insist you to learn the practical course, Jupiter will improve the theoretical concepts for this zodiac sign. Therefore, the year will be wonderful for most Gemini zodiac sign natives to practise whatever you have learnt. Also, the year is good for students interested in learning any professional course of their choice. Gemini 2021 Horoscope Shows Progress On The Health Front\n" +
"The year that passed by had challenges on the health front, the year 2021 will see a gradual subsiding of your ailments. The Gemini 2021 predictions show this will be a year where you will find all the health problems slowly taking a back seat. Medication if any that you have been enduring for long will also help you recover from the ailment at the earliest. One area that will need attention is your diet. Just make sure you are careful of your health in the following months February, May, and September 2021. Because Mercury will be retrograde around these three months.\n" +
"With the rise of income in the year 2021, the year is also likely to see a better phase in amassing wealth. Gemini native in the year 2021 can plan to acquire property, commodities and even seek credit to acquire these commodities. Thus, the asset base is likely to be much better in the year 2021. Seek credit assistance only to the extent that is needed, is the suggestion as per Gemini horoscope 2021.\n" +
"Again, the year will conclude well for native looking to get married. If you had any break up in the past and were unable to look forward, the year 2021 will enable you to slowly forget the past and look for a brighter future. The Gemini 2021 horoscope shows that singles will also find a good partner for their life and this will enable them to lead a beautiful romantic relationship. Eventually, marriage is on the cards. How will your relationship fare in the year 2021? Access the Free Personalized 2021 Report and get the answer.\n" +
"2021 Gemini Horoscope: An Overview\n" +
"This will be a year where Gemini zodiac will finally put an end to old issues and start afresh. You will be grateful to the transit of Jupiter in Aquarius whose aspect is also seen upon the Gemini zodiac sign. At the same time, there may be some progress on the health front. Some ailments from the past are likely to get treated during the year. Besides, you should seek credit assistance only to the extent that is needed, is the suggestion as per Gemini astrology prediction 2021.\n" +
"Cancer Horoscope 2021: Cancer 2021 Horoscope Shows A Challenging Year Ahead\n" +
"A year that will start on a sluggish note. 2021 as a year will be slightly challenging for natives of Cancer zodiac sign states of the Cancer horoscope 2021. The transit of Saturn in Capricorn and its hash aspect upon your sign will be difficult to sail through. But Saturn is known to reward hard work and efforts. Therefore, all those Cancer zodiacs sign native willing to put in their sweat are likely to improve their fortune. At the same time, Jupiter will be transiting over Aquarius that will contain the impediments, however will-not completely put a pause to the same. It would be important to continuously work hard and make new fortunes. Access your Free Personalized 2021 Report. Know whether your hard work will pay rich dividends in the year 2021.\n" +
"With the advent of 2021, the year will see a continuous rise in income as per Cancer horoscope 2021 predictions. As Jupiter is an aspecting income house of Leo and this will be the reason for improving income for the year. You will see the cash balance improving and this will enhance your fortune. However, the aspect of Saturn upon your sign from Capricorn will make you see an increase in expenditure. You will also see an increase in expenditure due to the transit of Jupiter through the zodiac sign Aquarius. Make sure that you do not rush up to any temptation and spend without looking up to the matter on hand as per Cancer 2021 horoscope.\n" +
"Cancer Horoscope 2021 Shows Misunderstanding With Your Partner\n" +
"Considering the personal and romantic life of the Cancer native, the year will be slightly challenging as misunderstandings will be the reason for fights as per Cancer yearly horoscope 2020. Saturn in the house of a partner and its aspect upon your sign will be the cause of misunderstanding. More so in the middle of the year starting from May till September 2020 as per the Cancer 2021. Around this phase, Saturn will also aspect the house of romance and love which will lead to continuous fights and personality clashes. You are advised not to be harsh and firm upon your point of view this year as per Cancer astrology prediction 2021.\n" +
"Having touched the issues of romance and love, other areas of life should also be analyzed. Such as education and academics. The year 2021 will demand more effort from students. Do not expect the support of luck to enhance your fortune as this will take away your scope of securing good grades. Again, the year is average for skills that enhance learning through formal education. You can however, take up vocational learning to improve your knowledge as you will put your knowledge in regular practice. This will enable you to improve your working knowledge for days to come, showing Cancer astrology 2021. Cancer Horoscope 2021: You Will Get Stability In Your Career\n" +
"With knowledge, the urge to earn money via a proper career will also be high this year. Cancer natives who have been looking for stability in their careers will find one. There will be more work and less time for leisure. You will be putting double efforts to make yourself felt within your company and organization. This effort from your side will give you success and elevate your position. Further, the year needs caution for those who have been looking to work on partnership business. Saturn aspecting your sign will not let you progress easily. Misunderstanding can be high and you will have to put them to rest amicably, states the Cancer 2021 yearly predictions.\n" +
"Along with a good career, health is also important and this is one area where Cancer natives will have to be careful. As Saturn is in its own house, it would make you quite sluggish and shall not let you enjoy a good sleep. Tension and worry will be there, in accordance with the 2021 Cancer horoscope. However, the good part is that the transit of Jupiter upon the sign of Aquarius will contain any serious ailments this year. This will come as a relief on your health front.\n" +
"Finally, the year will see a good accumulation of wealth. But wealth creation can happen only with the proper usage of money. Again, married life will see some disturbances, if you are already married. But thankfully Jupiter’s transit on the Aquarius Zodiac sign will enable some support from elders who will enable mediation and resolve differences of opinion. If you are looking for a partner for marriage, you should ideally wait for some time to settle down permanently as seen in the Cancer 2021 horoscope. Access the Free Personalized 2021 Report! Know about your marriage.\n" +
"2021 Cancer Horoscope: An Overview\n" +
"The year 2021 will not begin on a very good note. You may face several challenges which may be quite tough and difficult to deal with. The transit of Saturn in Capricorn and its hash aspect upon your sign will be difficult to sail through. However, things will get better with the passage of time. You are likely to get moderate to high success on various fronts of life as per the findings from Cancer horoscope 2021 predictions.\n" +
"Leo Horoscope 2021: Leo 2021 Horoscope: You Will Take Big And Bold Steps\n" +
"This is a year when your conviction in your decisions will be very strong as per your Leo horoscope 2021. While this will help you take some radical decisions, you will also need to be on your guard against becoming inflexible and stubborn. You will experience a deep emotional attachment with your loved ones as seen in Leo 2021. You will be in sync with your roots and family values. Those who love you will appreciate your progress, but there will be few who will envy your position and may want to tarnish your image. Beware of them! Your desire to learn and to expand the horizon of knowledge would be on the incline during this year. Know more about your academic activities in the year 2021. Buy the Free Personalized 2021 Report!\n" +
"You would be more effective in your communications with others than usual shows Leo 2021 predictions. Your logical and analytical abilities will flourish. You are likely to join communities, forums, and other social networks; as a result, your social circle will increase this year. If you have been ignoring something important related to your career or personal life for quite some time, such issues will raise their head and confront you, so says your Leo yearly astrology prediction.\n" +
"Leo Horoscope 2021 Says You May Add To Your Luxuries\n" +
"The Leo astrology prediction 2021 shows this year will increase the temptations to add luxury and comfort in your life. But, do not make a mistake of bringing an indulgent standard of living. If you cross your limits, it will be difficult for you to tackle commitment pressure and frustration will rise. Here, you will need to follow a very clear and defined path with very specific objectives. There will be a tendency to make decisions on the spur of the moment which may lead you to confusion.\n" +
"You will find yourself hassled by some minor issues in different areas of your life says your Leo horoscope 2021. They will require you to be on your toes. It is likely to leave you low on vitality at times. You may also feel irritated and those around you will end up bearing the brunt of your ire. There will be a noteworthy change in your thought process as the year progresses, and you will begin to get closer to your inner self. But, the problem is that you may be at times getting too negative or pessimistic in your thinking. It will be essential for you to cultivate an optimistic approach. Even if there are difficulties, your perseverance, spirituality, and occult may lead you in the right direction. So, this could be the best year to seek solutions from your seniors, elders, and spiritual masters. This could also be a good time to fight odds with the best of your abilities, wisdom, and patience. Keep your expectations low as per Leo astrology 2021. Leo Horoscope 2021: Avoid Being Carried Away By Emotions\n" +
"The Leo 2021 predictions say there will be times when you will feel like starting your life all over again. You shouldn’t get too carried away by your emotions. Be a little patient and keep faith. A little introspection may do the trick. You should pull up your socks and get ready to work even harder. You would have to withstand some stormy weather but, you will also have the strength to sail through efficiently. You have no option but to be positive and understand that there is no substitute for hard work. Long term planning and distancing yourself from short term gains and useless pursuits is likely to help build for the future. Seek advice and keep good terms with friends, loved ones, and well-wishers. Success will be there, but amid stiff challenges, so hang in there and keep putting efforts. Will your life be full of challenges in 2021? Buy the Free Personalized 2021 Report and know the answer.\n" +
"2021 Leo Horoscope: An Overview\n" +
"You may take some crucial important decisions which may change the flow of your life. However, you have to ensure that you don’t become inflexible and rigid in your approach as per the Leo horoscope 2021. Besides, you should avoid being overly emotional and impulsive. You may face tough times but you will have the ability to come out of them bravely.\n" +
"Virgo Horoscope 2021: irgo 2021 Horoscope: Surge Of Creativity Foreseen\n" +
"As per Virgo horoscope 2021, your time is good this year and you will be excited about some positive developments in your life. Creativity and enthusiasm will flow in whatever you do. You will also have a renewed interest in your life. However, when everything is moving in the right direction this year, it is essential for you to understand and to know what you are getting into, and what you are expecting out of it. You need to figure out the value before you take a step forward. You need to identify the opportunities early, and timely response to them is required or else you may miss the boat. Avoid being overconfident. Know about the opportunities that you may get in 2021. Access the Free Personalized 2021 Report!\n" +
"Career opportunities will abound. They will be in plenty. But the onus will be on you to make them happen. So, you will need to collect all your energies and mould them in such a manner that you can make the most of your life and situations. And it is seen that you will be able to do it, on the whole. So, it’s going to be a bright time for you, especially in the early months of the year. You will be able to rise in your career and build your destiny.\n" +
"But things don’t just end in seizing the opportunity. One also needs perseverance and a strong push to keep pursuing. Success usually is not a cakewalk. You know it well but then you have to be reminded to strengthen and re-establish your commitment. If you are able to preserve hard, you can do wonders.\n" +
"However, things may get difficult as the days roll on, that is around after April 2021. A new kind of pressure may bother you around the middle of this year, not just about your personality or your resources as per Virgo 2021 yearly horoscope. Rather, it will be more about mental output. Make sure you don’t lose your balance while making any fresh move or important decisions. You are likely to feel a kind of pressure to create new ideas and to make them work as you see a tremendous inflow of creativity this year. You may also feel some unusual pressure to structure your life and resources. However, you will gain a greater depth of understanding of your life and the experiences that you have during the middle of this year may enable you to make some wise decisions as per Virgo horoscope 2021. Virgo Horoscope 2021 Shows You Will Overcome Failures\n" +
"According to 2021 horoscope Virgo, this can be an important year of overcoming failures through constant hard work and perseverance. You may at times prefer a secluded environment and you may want to think more deeply about various issues in your life and such feelings will manifest strongly during the latter part of the year. This process to redefine your life and goals will bring clarity about how to proceed further in your life. Planetary positions during the ending months of the year will make you a bit of a philanthropist. Your intellect is going to be the key to success this year shows the Virgo 2021 horoscope. You will earn success thanks to your creativity, and the barrage of ideas that spout within you.\n" +
"The Virgo 2021 predictions show this year will be a period of literal re-organization of your internal and external world. Though most of the period of this year will remain supportive and positive, there will be phases when you will be drawn by some unknown fear or strange feelings. Here you need to make logic your tool to understand the complexity of everything around you. There can be flaws in your thinking or decisions, and only experience and analysis can help you sort out the problems. Use logic in the right direction and for constructive reasons, and you shall attain wisdom and success for sure. If you have your basics right, everything else will be just a matter of time. Now you need to look at the bigger picture, says Virgo astrology 2021. Read the Free Personalized 2021 Report! Know what achievements behold you in the year 2021.\n" +
"Virgo 2021 Horoscope: An Overview\n" +
"There will be a surge in your creativity and enthusiasm. There will be a positive flow in whatever you do. You will also have a renewed interest in your life. At the same time, when things will be moving in the right direction, you will have to be very careful. A little carelessness may turn out to be expensive. This may be on the personal front or the career front as per the 2021 Virgo horoscope. So, it’s going to be a good year overall.\n" +
"Libra Horoscope 2021: Libra Horoscope 2021: This Could Be Your Most Successful Year!\n" +
"According to Libra horoscope 2021, the year 2021 may prove to be one of the most successful years for you. With the transit of Saturn and Jupiter, placed in squares and trines respectively, the dual-energy of planets will enhance the benevolence in your life. Moreover, Saturn will bring stability in your personal life. Additionally, 4th house signifies domestic issues, thus you are likely to feel happiness and peace at home. The year 2021 may be less challenging for you as compared to last year. But you will have to be careful about the health of your mother, as per Libra yearly prediction 2021. So, you are advised to have regular health check-ups of your mother in order to avoid major health issues.\n" +
"As per the 2021 Libra horoscope, the year 2021 may bring many surprises in your life. However, the astrological prediction in Libra 2021 horoscope says that, due to a strong placement of Jupiter in Aquarius and its direct aspect on your zodiac sign, there are chances of a hike in income from the regular source. You can even expect an increment in your present job and a certificate of recognition. Thus, you are likely to be happy to receive both monetary appreciation and recognition, as per Libra horoscope 2021. In case you are into business, there are chances of increment in your business income. Additionally, you can look for an alternative source to boost your overall business income. The revenue stream will be encouraging to you in the year 2021. To know the favourable phase for business in the year 2021, access your Free Personalized 2021 Report!\n" +
"Not only this but the year 2021 is also best if you are opting for higher studies. The transit of Saturn in Capricorn and the transit of Jupiter in the zodiac sign of Aquarius will be encouraging, as per Libra 2021 prediction. However, the effect of planetary transit may differ depending on the other placements of planets in your birth chart. Additionally, this may be the year where you will be able to study hard and even improve your learning skills with better retention. Furthermore, Jupiter transit in Aquarius will improve your creative skills and if you are taking part in any creative competition, you are likely to do well. You are advised, not to be overconfident while taking part in any competition.\n" +
"Libra Horoscope 2021: It’s Your Time To Shine!\n" +
"As per Libra horoscope 2021, if you have had to face many challenges in your career last year, then 2021 has something interesting and important for you. We know that there were impediments in the progress last year which led to some discontentment in your life, you were not comfortable to see any light of hope that gave you signs for betterment. However, the year 2021 will provide you many opportunities, do not let these opportunities slip away, as per the 2021 Libra horoscope.\n" +
"According to Libra yearly horoscope 2021, you are likely to improve your career development. The aspect of Saturn upon the career house will make you work hard and at the same time the aspect of Jupiter in the house of gains will give you steady progress in your efforts. Therefore, with the help of hard work and good luck, you are likely to achieve success in all the endeavors that you undertake.\n" +
"Moreover, benevolence will also be seen in the area of business and self-employment. Also, new assignments may give you recognition and even an opportunity to prove your credentials. It’s time for you to shine and make a comeback, bring out your hidden talent. Libra 2021 Horoscope: Happiness Lies In Good Health!\n" +
"You will be able to enjoy your life, only if you are able to maintain good health. According to Libra horoscope 2021, you will be able to easily channelize your energy in the right direction and achieve the desired target. As per Libra 2021 predictions, the impact of Jupiter and Saturn, along with sign lord Venus will be quite supportive for you. Not only this, but you will also be able to maintain your health if you take care of your diet and exercise regularly. It will help you improve your stamina and immunity. The astrology prediction in Libra 2021 horoscope says that the month of February, March, and April 2021 will be particularly good as the favorable position of the planets may enhance your energy level.\n" +
"2021 Libra Horoscope: Enhance Your Wealth & Marriage Prospects\n" +
"Also remember, when the health is good, then and only then, your energies can be channelized into the productive effort. According to the Libra 2021 horoscope, there are strong indications that you are likely to improve your wealth as you will be more focused and determined towards your work. Furthermore, the year 2021 is good for renovating your house, even owning a second house, or even investing in real estate projects to improve your equity participation. But stay cautious and think twice before making any investment in real estate.\n" +
"Finally, if you are planning to get married in 2021, then the year 2021 is one of the most auspicious years to settle down. Your family and close friends will be happy with your decision and will support you and help you at an important moment.\n" +
"Scorpio Horoscope 2021: Scorpio 2021 Horoscope: You May Receive Many Opportunities For Financial Gain!\n" +
"According to Scorpio horoscope 2021, the year may bring mixed results for Scorpio individuals. As the year 2021 will progress, you are likely to be more energetic, courageous, and even be able to stick to your new year resolutions. Moreover, the transit of Saturn in Capricorn will make you courageous and the transit of Jupiter in Aquarius will make you stick firm on the decision that you would take out of courage. As per 2021 Scorpio horoscope, the year may be quite progressive as you will be determined to achieve what you are clear to achieve.\n" +
"Additionally, there are high chances that you may get many good opportunities for financial gains. However, earnings may be moderate, but the sources are likely to be robust and may give long term returns. Moreover, you may also find the outcome of the earnings becoming stable and steady. You also may be admired by your peers and friends about identifying the opportunity and then giving a steady focus upon the same. According to Scorpio 2021 predictions, it may be one of your memorable years as you are likely to achieve your goals through your determination and hard work. Know the obstacles that may stop you to achieve your goals and prepare for it in advance with your Free Personalized 2021 Yearly Report!\n" +
"Scorpio Horoscope 2021: Peace And Harmony In Relationship\n" +
"According to Scorpio astrology prediction 2021, the year is likely to be favorable for you in respect to Love and relationship. If you are already in a relationship, then this may prove good for your relationship. Moreover, the transit of Saturn and Jupiter will bring stability in your relationship. You will be happy with the relationship that you have been leading and shall also see a steady rise in social status. But for singles the year may not have much good news to offer. If you are single, then this year you may be unable to find one partner to lead a good life, says Scorpio horoscope 2021. Make sure you do not lose your hope as the end of the year will give some light moments with someone special. This will slowly blossom into a romantic relationship in the years to come. To get more love insights, check Scorpio love horoscope 2021.\n" +
"Scorpio Horoscope 2021: Favorable Year For Academics!\n" +
"The other good area of improvement this year will be your academics and practical learning. According to Scorpio 2021 horoscope, Saturn and Jupiter may enable you to learn very well and even make you apply your knowledge practically. Furthermore, Saturn is well placed to make you practice what you have learned and Jupiter will coordinate very well with your conceptual knowledge. Therefore, learning will be encouraging and rewarding in the days to come. Additionally, students and individuals planning to pursue any skill that is unique and in demand, must learn the same and practice this year. The year 2021 may prove to be a wonderful year for improving your skills and knowledge. Scorpio Horoscope 2021: New Career Opportunities Are Foreseen!\n" +
"According to Scorpio astrology 2021, there are high chances of getting many new career opportunities. New initiatives may be rewarding and you will find the career progress in a much rewarding fashion. But at the same time, you will need to bring stability in your career by exploring new avenues to work and experiment with its earnings. Your efforts will be good and it would be rewarding in the long run. Even if you are planning to take up an independent venture, then it may turn out to be a rewarding phase for you. Scorpio 2021 horoscope says the aspect of Jupiter upon the career house will make you progressive and successful. Furthermore, Saturn in Capricorn will make you take risks and even take them successfully.\n" +
"According to Scorpio horoscope 2021, with the transit of Saturn is well placed, the year 2021 will be also good as far as your health is concerned. You are likely to enjoy good stamina and even remain fit. Moreover, Jupiter transit in Aquarius may make you fit. As per Scorpio 2021 horoscope prediction, you will be health-conscious and shall also take adequate importance of your diet. To get guidance for your next career move, refer Scorpio career horoscope 2021. Additionally, with the help of Free Personalized 2021 Yearly Report, you can know favourable periods for starting any new project.\n" +
"2021 Scorpio Horoscope: The Year May Enhance Wealth Prospects!\n" +
"Further, the year will be good for wealth acquisition. Additionally, Jupiter in the zodiac of Aquarius will accentuate the opportunity to acquire wealth. As per Scorpio yearly horoscope 2021, you are likely to be successful in all walks of life of accumulating wealth. However, if you are trying to see credit or loans then this can later reduce your income earning capacity.\n" +
"According to Scorpio horoscope 2021, the year 2021 may enhance marriage prospects. The year may be favorable for you if you are planning to marry your beloved. Scorpio 2021 horoscope says that you are likely to be happy in your married life. Ganesha suggests you be more understanding of your partner and avoid arguments. Additionally, try to maintain temperament.\n" +
"Sagittarius Horoscope 2021: Sagittarius Horoscope 2021: Favourable Year For Your Career & Academics!\n" +
"According to Sagittarius astrology prediction 2021, the year 2021 is likely to bring many surprises for you. Moreover, there is something for all age groups this year, which will delight one and all. Prosperity, success, and fortune are likely to manifest across the year to please you. There are chances that your education and higher studies may be impressive and fulfilling, says Sagittarius 2021 horoscope. As the year will progress, you may also realize that the luck and divine grace is here to stay.\n" +
"As per the Sagittarius yearly horoscope 2021, the initial four months of the year are likely to be spent in planning your activities. Energy levels will be high and so is your enthusiasm. There is a high possibility of being meticulous in your action and may also try to leave no stone unturned. According to Sagittarius 2021 predictions, the effects of good planning and execution will be seen for the rest of the eight months of the year 2021. The astrology predictions may differ based on other planetary positions in your birth chart. Access Free Personalized 2021 Yearly Report!\n" +
"Sagittarius Horoscope 2021: New Connections Are Foreseen!\n" +
"As per horoscope 2021 Sagittarius, this year may be favorable to expand your social circle. You are likely to be in the spree to meet new people and even new friends. The association with new friends may turn beneficial in the days to come. Moreover, if you are looking out for that one special person who can please your mind and heart, then the chances are high to fall in love with such a special person within the start of the first three months.\n" +
"According to the Sagittarius astrology 2021, Saturn will transit in the 2nd house of income and family, thus, you are likely to maintain a perfect balance of the two. Work will look interesting as your work may directly lead to a rise in income. Additionally, this may give you a better state in society and shall make you proud of your achievements in career.\n" +
"Academically, students pursuing Mass media or planning to pursue the same can successfully find their enrolment in one of the reputed institutes in the world through hard work. According to the 2021 Sagittarius horoscope, it may give you the recognition that you have been working for a very long time. The year is also good for students planning to pursue a Master’s program in metallurgical science. If writing any thesis on the subject, then your findings are likely to be appreciated and even felicitated.\n" +
"2021 Sagittarius Horoscope: There are chances of delay in receiving the desired results from your business!\n" +
"According to Sagittarius horoscope 2021, business and professional excellence may come in a delayed fashion. However, you will see positive results with the help of your hard work and determination. The initial three months may see some review of your past work. Moreover, this may involve brainstorming and even identifying new avenues to explore business. Make sure your business plan is perfect and flawless as your remaining part of the year will see maximum time in the implementation of your plan. Sagittarius 2021 Horoscope: Stay Cautious About Your Diet!\n" +
"As per the 2021 Sagittarius horoscope, you are likely to be free from the affiliation of the nodes (Rahu and Ketu). Additionally, the year will be more progressive with regard to health and fitness. You are likely to be conscious of your diet and fitness and this will be visible in your routine activities. Good sleep will reduce mental stress and will make you emotionally more stable and fit, says Sagittarius 2021 yearly horoscope.\n" +
"Sagittarius Horoscope 2021: You are likely to maintain work-life balance!\n" +
"According to Sagittarius 2021 horoscope, wealth and property may see a rise in finance through various sources. There are chances that income and expenditure may see an act of balancing your finance, especially in business or self-employment. The conjunction of Saturn and Jupiter is ideal to help you take up most of your time to analyze the sources and verify its feasibility, says Sagittarius prediction 2021. Ganesha suggests you complete this exercise before April 2021 to get the best deal in negotiation. Chances are high that you may easily convince the financial institution of your steady repayment track record to enjoy a good deal. To grab the opportunities coming in the year 2021 at the right time, access your Free Personalized 2021 Report!\n" +
"Sagittarius 2021 Horoscope: You may face challenges in your relationship!\n" +
"Sagittarius horoscope 2021 predictions say that native dating each other for long may plan to tie the nuptial knot. This may be a year in which you may face many ups and downs and also, differences of opinion. With the transit of Jupiter into Aquarius sign around April 2021, there are chances of postponing your marriage plan, according to Sagittarius 2021. There are also chances of silly arguments or reasons which can lead to a temporary separation, only to get a patched-up later. Though you can easily patch-up, the response will take time until the end of August 2021. Ego clash should ideally be restricted around this phase.\n" +
"Capricorn Horoscope 2021: Capricorn 2021 Horoscope: Think Twice Before Making Important Decisions!\n" +
"The year 2021 is likely to be a year with heavy transit which may impact your life. According to Capricorn horoscope 2021, the year 2021 may make you introspect in your actions and may induce you to make adjustments. These changes may decide the future of your actions. In fact, the decision that you may take now and then follow it with actions will decide the outcome during the year, says Capricorn 2021 predictions. Therefore, our expert astrologers suggest you make sure you think deeply before you decide to make a decision and take action. You access your Free Personalized 2021 Yearly Report, it will guide you towards the right direction.\n" +
"One of the first steps that you may take is to rejig your finance. According to the 2021 Capricorn horoscope, the transit of Jupiter and Saturn may make you spend, but on a calculative mode. Moreover, Saturn, being the lord of Finance to your zodiac sign and Jupiter bring the house of loss, together will put you to work on those finance areas that will be secondary and irrelevant. Planning on investments and even controlling your expenses are likely to be the first step, according to Capricorn astrology prediction 2021. If married, then you may keep a portion of your savings for future commitments. Just try to make this a routine practice.\n" +
"Capricorn Horoscope 2021: You Are Likely To Spend Quality Time With Your Partner!\n" +
"However, the year 2021 will be good for love and relationships, as per Capricorn horoscope 2021 astrology predictions. The ego clash that prevailed in the past may now completely subside. This is likely to improve the bonding of the two sides throughout the year. As Jupiter is out of the friction this year, you may be happy with your partner to spend a romantic moment, according to the Capricorn 2021 horoscope. These were some interesting instances that you missed for long. Capricorn Horoscope 2021: The Year 2021 Is Likely To Be Good For Students!\n" +
"Further the year 2021 is likely to be good for students planning to pursue higher studies, especially in the area of research and experimentation. The combination of Jupiter and Saturn may make you good at taking up areas of study that may include Finance, Language, and Engineering. As per Capricorn 2021 horoscope, the transit of Venus around March and April can also give a boost to students who are interested in fine arts or creative studies. You may even take one of the subjects as your majors and master the same. This can support your career decision in the long run, says astrological prediction of Capricorn in 2021.\n" +
"When academics are supportive, will this also support your career and business graph? Then the answer is yes! According to Capricorn 2021 horoscope, the year is good for career progress, if you are stepping out of high school or university exams. Though the first two quarters of the year are likely to be challenging, the second half of the month may give you many opportunities to settle down. A little patience will be ideal to help you. Further for those who are already employed, the year will be progressive, according to Capricorn horoscope 2021. Returns of your hard work are likely to be interesting, but you will have to take up your work seriously. Plan your career accordingly this year.\n" +
"2021 Capricorn Horoscope: Stay Cautious About Your Health!\n" +
"According to Capricorn horoscope 2021, the one area that will demand attention this year will be your health. Given the transit of Saturn and Jupiter, the dual transit is likely to make your year stressful. But despite being stressed, you may also be careful of your fitness by taking up adequate sleep to keep yourself fit and healthy. As per Capricorn 2020 predictions, the transit of Jupiter in Aquarius for the whole year will bring grace in your life. Therefore, this may improve your fitness and health.\n" +
"When health is well maintained, you can automatically develop an inclination to gain good wealth. Therefore, the year 2021 will be slow, but steady to maintain and improve your position in wealth. According to the horoscope 2020 for Capricorn, if you are into business, then you are advised to be careful this year. If planning to expand or looking for a long-term investment scheme, then the year is not likely to be supportive. Try to avoid investing in long term schemes. Free Personalized 2021 Yearly Report can help you plan your next career move and alert you of the upcoming possible challenges.\n" +
"Capricorn Horoscope 2021: Favorable Year For Marriage!\n" +
"Again, if planning to marry, then the year is very good to decide the same. Starting from January 2021, the year will bring many good proposals for marriage that you can consider. The good part is that you may marry the person whom you know for ages.\n" +
"Aquarius Horoscope 2021: Aquarius 2021 Horoscope: Initially, you may face some challenges\n" +
"As per Aquarius astrology prediction 2021, the year is likely to be giving you more experience than usual. With the sign lord Saturn being in the 12th house for your sign, the initial few months may see a rise in tension and you may face some challenges. Furthermore, the conjunction of a debilitated Jupiter may cause some issues in your life. Additionally, being the lord of 2nd and 11th, it may add to the stress and tension. Many of your planning may not be as per the scheduled activities, and this may lead to some disappointment initially. For you, these events may be a first-time experience that can be emotionally taxing. However, as the year 2021 will progress, you are likely to be happy with the way life may turn events in your favor. Additionally, with Free Personalized 2021 Yearly Report you can know the favourable periods of investment based on your birth chart.\n" +
"According to the 2021 Aquarius horoscope, the positive part of the year 2021 is the transit of Jupiter in your zodiac sign from April 2021. The transit of Jupiter is considered very auspicious in areas of finance and wealth, romance, marriage, education, profession, and even in expanding social circles. Therefore, you are likely to see an expansion in your life in all the above matters that were discussed and shall be happy with the progress you will enjoy.\n" +
"But initially, the year 2021 will have some stringent moments with regard to finance and money, says Aquarius yearly horoscope 2021. You may see a continuous and steady rise in expenditure that may make you dizzy at times. There may be occasions where the expenditure will be more than your income. This may force you to rely on short term credit, as per the 2021 horoscope Aquarius. Make sure such credits are only restricted up to the short term, as such credit can tempt you to take major risks, especially in the first few months of the year. Gradually from the middle of the year, you are likely to see a steady rise and the second half of the year will be better than the first half. In fact, the year may be promising for you, if you are looking to invest in property. Be it a first purchase or an investment, you may enjoy seeing options before investment. Aquarius Horoscope 2021: You are likely to find your life partner\n" +
"Further, the year 2021, may bring some exciting surprises for you, says Aquarius 2021 predictions. From the middle of the year, there is a high probability that you may come across some important person in your personal life. The emotional connection with this new person shall sow the seeds of romance and love. You may soon be connected to a romantic relationship with this special person. The love and concern that was a vacuum in your life as an individual is now likely to be filled by this special person. Gradually the two of you may even decide to settle down in a permanent relationship of marriage. Your emotional bond will turn out to be a legal bind.\n" +
"Aquarius 2021 Horoscope: Favourable year with respect to career and education\n" +
"According to the Aquarius horoscope 2021 yearly prediction, the transit of Jupiter in your sign will be auspicious for students planning to pursue higher studies. Your dedication and efforts may pay you good results since the start of the month. If you have already taken a clear plan of your action, then you may be successful in executing the same this year. In fact, your dedication and hard work are the core of every success that you enjoy during the year as per Aquarius 2021 horoscope.\n" +
"With the prospects of a good education, the future of a better career is also promised. Make sure you are clear with your fundamental knowledge, as you may also enjoy a good campus placement opportunity. Even if you are looking for a new opportunity, then you are likely to find one, with the help of your efforts and networking skills, says Aquarius horoscope 2021. After May 2021, if you are keen on starting an enterprise, then there is a high possibility that you may pursue your dream and start your own business. You can access Free Personalized 2021 Yearly Report, it will help you to put your efforts in the right direction.\n" +
"Aquarius Horoscope 2021: Stay cautious about your health\n" +
"When it comes to health, Aquarius individuals are known to be more careful with regard to their fitness and routine activities. You are particular to your diet and even make sure you take the food at the appropriate time during the day. This discipline can slightly get disturbed as your appetite is likely to increase, so is your food intact, according to the 2021 Aquarius horoscope. You will have to be careful with your diet intake now. This may help you to maintain your fitness and boost your immunity.\n" +
"Pisces Horoscope 2021: Pisces Horoscope 2021: Your dreams may come true this year based on your efforts\n" +
"According to Pisces horoscope 2021, the year 2021 is likely to bring mixed-results initially for you. At the start of the year, the sign lord Jupiter is well placed in the 11th house of gains. Albeit debilitated, it would be encouraging as the conjunction of Saturn and Jupiter is likely to bring steady progress, says Pisces 2021 horoscope. There are chances that your desire may be fulfilled, based on the efforts that you will apply. This will make you feel confident.\n" +
"As per the 2021 Pisces horoscope, the house of gains is robust, the start of the year is likely to see an increase in income and the outflow of money tapering considerably. You may save more for the hay days and this may give you some breather to deal with the future. This process may continue until the end of April 2021 and then the flow of income will stabilize to merely meet the expenditure. According to the Pisces astrology 2021, you will have to guard yourself against a sudden spike or rise in expenditure. Little planning can turn the event in your favor. Free Personalized 2021 Yearly Report can alert you about the upcoming challenges in advance so that you can be prepared for them.\n" +
"Pisces 2021 Horoscope: Some new connections and financial stability are on cards\n" +
"In fact, at the start of the year, you may take part in many social gatherings and parties, which is likely to turn out to be beneficial. New friends and associations may be forged between January till April 2021 who shall be instrumental in elevating your social status. This may again see a boost around September and October 2021 where the association may be at its peak. As per Pisces horoscope 2021 predictions, you are advised to get along with the high and mighty, to maximize your gains.\n";
}
